create table public.refresh_token
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       bigint       not null references public.user (id),
    token         varchar(255) not null,
    expiration_date    timestamp with time zone  not null
);