CREATE type user_role as enum ('ROLE_USER', 'ROLE_ADMIN');

CREATE type lobby_type as enum ('PUBLIC', 'PRIVATE');


CREATE TABLE IF NOT EXISTS public.lobby
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kind lobby_type NOT NULL,
    creation_date timestamp without time zone NOT NULL
);


CREATE TABLE IF NOT EXISTS public.user
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role user_role NOT NULL,
    lobby_id bigint,
    CONSTRAINT user_entity_lobby_id_fkey FOREIGN KEY (lobby_id)
        REFERENCES public.lobby (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
);